service: serverless-aliyun-test

provider:
  name: aliyun
  runtime: nodejs8
  credentials: /home/jiangzhuo/Desktop/serverless-aliyun-test/aliyun_credential # path must be absolute

plugins:
  - serverless-aliyun-function-compute
  - serverless-plugin-typescript
package:
  include:
    - src/**/*.graphqls
  exclude:
    - package-lock.json
    - .gitignore
    - .git/**

functions:
  graphql:
    handler: src/graphql.handler
    initializer: src/graphql.initializer
    timeout: 10
    events:
      - http:
          method: any
          path: /graphql
  upload:
    handler: src/upload.handler
    initializer: src/upload.initializer
    timeout: 10
    events:
      - http:
          method: any
          path: /upload
  download:
    handler: src/download.handler
    initializer: src/download.initializer
    timeout: 10
    events:
      - http:
          method: any
          path: /download
