service: serverless-aliyun-test

provider:
  name: aliyun
  runtime: nodejs8
  credentials: /home/jiangzhuo/Desktop/serverless-aliyun-test/aliyun_credential # path must be absolute

plugins:
  - serverless-aliyun-function-compute
  - serverless-plugin-typescript
package:
  include:
    - src/**/*.graphqls
  exclude:
    - package-lock.json
    - .gitignore
    - .git/**

functions:
  hellographql:
    handler: src/main.handler
    initializer: src/main.initializer
    timeout: 10
    events:
      - http:
          method: any
          path: /graphql
